version: '3.8'

services:
  siba_db_deployment:
    image: mariadb:latest
    container_name: siba_db_container
    env_file:
      - .env.db
      - .env.db.root
    ports:
      - '3306:3306'
    volumes:
      - ./Database/SQL_Scripts/000__CreateALLdb.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    networks:
      - db_be_network

  siba_be_deployment:
    container_name: siba_be_container
    build: .
    env_file:
      - .env.be
      - .env.db
    depends_on:
      - siba_db_deployment
    environment:
      - DB_HOST=siba_db_deployment
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - db_be_network

  reverseproxy:
    env_file: .env.reverseproxy
    image: nginx:alpine
    container_name: siba_reverse_proxy
    depends_on:
      - siba_be_deployment
    ports:
      - "3000:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - "${SSL_CERT_PATH}:/etc/nginx/ssl/fullchain.pem"
      - "${SSL_KEY_PATH}:/etc/nginx/ssl/privkey.pem"
    networks:
      - db_be_network

networks:
  db_be_network:
    driver: bridge

volumes:
  mariadb_data: