version: '3.8'

services:
  siba_db_deployment:
    image: mariadb:latest
    container_name: siba_db_container
    env_file:
      - .env.db.credentials
      - .env.db.root
    ports:
      - '3306:3306'
    volumes:
      - ./Database/SQL_Scripts/000__CreateALLdb.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    networks:
      - db_be_network

  siba_be_deployment:
    container_name: siba_be_container
    build: .
    env_file:
      - .env.be
      - .env.db.credentials
    depends_on:
      - siba_db_deployment
    environment:
    - DB_HOST=siba_db_deployment
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - db_be_network

networks:
  db_be_network:
    driver: bridge

volumes:
  mariadb_data: